---
deployment:
  tasks:
    - export DEPLOYPATH=$HOME/public_html
    - export REPOPATH=$HOME/repositories/glpi/*
    - /bin/rsync -rlP --delete --exclude '/.git' --exclude '/README.md' --exclude '/.gitignore' --exclude '/.gitlab-ci.yml' ${REPOPATH}/ $DEPLOYPATH --verbose
    - /bin/find $DEPLOYPATH -type d -exec /usr/bin/chmod 755 '{}' \;
    - /bin/find $DEPLOYPATH -type f -exec /usr/bin/chmod 644 '{}' \;

 
